[package]
name = "llm-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
copypasta = "0.10.1"
crossterm = "0.28.1"
ratatui = "0.28.1"
serde = "1.0.209"
serde_json = "1.0.127"
shell-escape = "0.1.5"
textwrap = "0.16.1"
unicode-width = "0.1.13"
